import { ContentDialog } from "../components/ContentDialog";
import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Button } from "@sb/ui";
import { LibraryGameSchema, type ContentData, type LibraryGame } from "@sb/contracts";
import { api } from "../lib/api";
import { useContent, readImage, message } from "../lib/content";
import { ContentGate, ContentNotice, GamePicker } from "../components/ContentTools";
import { JournalCaptures } from "../components/JournalCaptures";
type Entry=ContentData["journal"][number];
export function JournalPage(){return <ContentGate><Journal/></ContentGate>;}
function Journal(){
  const c=useContent(),[params]=useSearchParams();const initial=params.get("game")??"";
  const [gameId,setGameId]=useState(initial),[picked,setPicked]=useState<LibraryGame|null>(null),[draft,setDraft]=useState<Entry|null>(null),[error,setError]=useState(""),[image,setImage]=useState<string|null>(null),[removed,setRemoved]=useState<Entry|null>(null);
  useEffect(()=>{if(!initial)return;let live=true;void api.game(initial).then(g=>{if(live)setPicked(LibraryGameSchema.parse(g));}).catch(e=>{if(live)setError(message(e));});return()=>{live=false;};},[initial]);
  const choices=[...new Map([...(c.data?.games??[]),...(picked?[picked]:[])].map(g=>[g.universeId,g])).values()];
  const entries=(c.data?.journal??[]).filter(e=>!gameId||e.universeId===gameId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  const create=()=>{if(!gameId){setError("Choose a game first.");return;}setDraft({id:crypto.randomUUID(),universeId:gameId,title:"",text:"",createdAt:new Date().toISOString(),images:[]});setError("");};
  return <div className="content-page"><header className="content-heading"><div><h2>Journal</h2><p className="sb-muted">Private notes and screenshots, saved on this PC.</p></div><Button disabled={!c.data||c.busy||!gameId} onClick={create}>New entry</Button></header><ContentNotice error={error||c.error}/>{c.loading&&<p>Loading your journal…</p>}{c.error&&<Button onClick={()=>void c.reload()}>Reload journal</Button>}
    <label className="content-toolbar">Game<select className="sb-input" value={gameId} onChange={e=>setGameId(e.target.value)}><option value="">All games</option>{choices.map(g=><option key={g.universeId} value={g.universeId}>{g.name}</option>)}</select></label><details className="sb-card content-panel"><summary>Find another game</summary><GamePicker onPick={g=>{setPicked(g);setGameId(g.universeId);}}/></details>
    <JournalCaptures gameId={gameId}/>
    {removed&&<div className="content-toolbar"><span>Entry removed.</span><Button disabled={c.busy} onClick={async()=>{if(await c.save(d=>{d.journal.push(removed);}))setRemoved(null);}}>Undo</Button></div>}
    {!entries.length&&!c.loading&&<p className="content-empty">Choose a game and capture a note, a goal or a screenshot from your session.</p>}
    {entries.map(entry=><article className="sb-card content-panel journal-entry" key={entry.id}><div className="content-heading"><div><small className="sb-muted">{choices.find(g=>g.universeId===entry.universeId)?.name??`Game ${entry.universeId}`} · {new Date(entry.createdAt).toLocaleString()}</small><h3>{entry.title}</h3></div><div className="content-toolbar"><Button variant="ghost" onClick={()=>{setDraft(structuredClone(entry));setError("");}}>Edit</Button><Button variant="ghost" disabled={c.busy} onClick={async()=>{if(await c.save(d=>{d.journal=d.journal.filter(e=>e.id!==entry.id);}))setRemoved(entry);}}>Remove</Button></div></div><p className="journal-text">{entry.text}</p><div className="journal-images">{entry.images.map((src,i)=><button key={i} onClick={()=>setImage(src)} aria-label={`Open screenshot ${i+1}`}><img src={src} alt={`Screenshot ${i+1}`} loading="lazy"/></button>)}</div></article>)}
    {draft&&<ContentDialog onClose={()=>setDraft(null)}><form role="dialog" aria-modal="true" aria-label="Journal entry" className="sb-card content-modal" onSubmit={async e=>{e.preventDefault();if(await c.save(d=>{const game=choices.find(g=>g.universeId===draft.universeId);if(game&&!d.games.some(g=>g.universeId===game.universeId))d.games.push(game);d.journal=[...d.journal.filter(v=>v.id!==draft.id),draft];}))setDraft(null);}}><h2>{draft.title||"New entry"}</h2><ContentNotice error={error||c.error}/><label>Title<input className="sb-input" required maxLength={100} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Notes<textarea className="sb-input" rows={7} maxLength={16000} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/></label><label className="content-file">Attach screenshots (up to 4, 1 MB each)<input type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={async e=>{const files=[...(e.target.files??[])];if(files.length+draft.images.length>4){setError("Attach up to four screenshots per entry.");return;}try{const images=await Promise.all(files.map(readImage));setDraft({...draft,images:[...draft.images,...images]});setError("");}catch(e){setError(message(e));}}}/></label><div className="journal-images">{draft.images.map((src,i)=><button type="button" key={i} aria-label={`Remove screenshot ${i+1}`} onClick={()=>setDraft({...draft,images:draft.images.filter((_,n)=>n!==i)})}><img src={src} alt={`Screenshot ${i+1}`}/><span>Remove</span></button>)}</div><div className="content-toolbar"><Button disabled={c.busy||!draft.title.trim()}>Save entry</Button><Button type="button" variant="secondary" onClick={()=>setDraft(null)}>Cancel</Button></div></form></ContentDialog>}
    {image&&<ContentDialog onClose={()=>setImage(null)}><div className="journal-lightbox"><Button onClick={()=>setImage(null)}>Close</Button><img src={image} alt="Journal screenshot"/></div></ContentDialog>}
  </div>;
}
